USE jugos;
SELECT * FROM tb_clientes;
ALTER TABLE tb_clientes ADD PRIMARY KEY(DNI);

ALTER TABLE tb_clientes ADD COLUMN(FECHA_NACIMIENTO DATE);

INSERT INTO tb_clientes(
DNI,
NOMBRE,
DIRECCION1, 
DIRECCION2, 
BARRIO, 
CIUDAD, 
ESTADO,
CP,
EDAD,
SEXO,
LIMITE_CREDITO,
VOLUMEN_COMPRA,
PRIMERA_COMPRA,
FECHA_NACIMIENTO) VALUES('456879548', 'Pedro Páramo', 'Calle del Sol 25', '',
'Los Laureles', 'CDMX', 'México', '65784', 55, 'M', 1000000, '2000', 0, '1970-04-14'
)


